org: ssp6sean
app: web3-api
service: web3-api

# Create an optimized package for our functions
package:
  individually: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: '20201221'


functions:
  signIn:
    handler: src/handlers/apis.signIn
    environment:
      JWT_SECRET: ${env:JWT_SECRET}
    events:
      - httpApi:
          path: /signIn
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
