org: ssp6sean
app: web3-api
service: web3-api

# Create an optimized package for our functions
package:
  individually: true
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  lambdaHashingVersion: '20201221'
  httpApi:
    cors: true
plugins:
  - serverless-plugin-typescript
  - serverless-offline


functions:
  signIn:
    handler: src/handlers/apis.signIn
    environment:
      JWT_SECRET: ${param:JWT_SECRET}
    events:
      - httpApi:
          path: /signIn
          method: post
          cors:
            origin: '*'
            allowCredentials: true
  userHasAccess:
    handler: src/handlers/apis.userHasAccessCookies
    environment:
      JWT_SECRET: ${param:JWT_SECRET}
    events:
      - httpApi:
          path: /userHasAccess
          method: post
          cors:
            origin: '*'
            allowCredentials: true
